---
apiVersion: v1
appVersion: 1.2.1
description: A Helm chart for installing PrivateBin
name: privatebin
home: https://privatebin.info/
icon: https://raw.githubusercontent.com/PrivateBin/assets/master/images/preview/icon.png
version: 0.2.4
maintainers:
  - name: bdashrad
    email: bdashrad@gmail.com
sources:
  - https://github.com/PrivateBin/PrivateBin
  - https://github.com/PrivateBin/docker-nginx-fpm-alpine
keywords:
  - pastebin
  - PrivateBin
  - ZeroBin
