---
name: Lint and Test Chart
on: pull_request

jobs:
  lint-and-test:
    name: Lint and Test ${{ matrix.kubernetesVersion }}
    strategy:
      fail-fast: false
      matrix:
        kubernetesVersion: [
          "v1.14.10",
          "v1.15.7",
          "v1.16.4",
          "v1.17.2",
        ]

    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: lint
          config: .ci/ct-config.yaml

      - name: Install kind
        uses: helm/kind-action@v1.0.0-alpha.3
        with:
          node_image: "kindest/node:${{ matrix.kubernetesVersion }}"
          config: .ci/kind-config.yaml
          install_local_path_provisioner: true
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Verify kind
        run: |
          kubectl cluster-info
          kubectl get nodes -o wide
          kubectl get pods -n kube-system
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: install
          config: .ci/ct-config.yaml
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'
